name: Regression test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build Petasearch
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j $(nproc --all)

      - name: Download databases
        run: |
          mkdir -p databases
          srasearch databases UniProtKB/Swiss-Prot databases/swissprot tmp

      - name: Build target dbs
        run: |
          srasearch convert2sradb databases/swissprot databases/swissprot_sra
          srasearch createkmertable databases/swissprot_sra databases/swissprot_kmertable
          echo -e "databases/swissprot_kmertable\tdatabases/swissprot_sra" > targetdbs
          echo -e "databases/res_compk" > resultlist

      - name: Build query db
        run: |
          sed 's/-//g' tests/MSA_Cas7-11_multiline.fa > tests/Cas7-11.fasta
          srasearch createdb tests/Cas7-11.fasta tests/querydb
          
      - name: Reformat MSA to Stockholm
        run: |
          chmod +x tests/reformat.pl
          tests/reformat.pl fas sto tests/MSA_Cas7-11_multiline.fa tests/MSA_Cas7-11_multiline.stockholm

      - name: Build query profile db
        run: |
          srasearch convertmsa tests/MSA_Cas7-11_multiline.stockholm tests/msadb
          srasearch msa2profile tests/msadb tests/query_profile
          srasearch petasearch tests/querydb targetdbs resultlist alignments.m8 tmp
          srasearch petasearch tests/query_profile targetdbs resultlist alignments_profile.m8 tmp
