name: Regression test

on:
  push:
  pull_request:
    branches:
      - main
      - master


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Set up cmake build system
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          cmake --version
          gcc --version

      - name: Build Petasearch
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          cd ..

      - name: Test build
        run: |
          build/src/srasearch --help

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: petasearch
          path: build/src/srasearch

  regression:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: petasearch

      - run: chmod +x srasearch
      - run: echo $(pwd) >> $GITHUB_PATH

      - run: srasearch --help

      - name: Download databases
        run: |
          mkdir -p databases
          cd databases
          srasearch databases UniProtKB/Swiss-Prot swissprot tmp
          cd ..

      - name: Build target dbs
        run: |
          srasearch convert2sradb databases/swissprot databases/swissprot_sra
          srasearch createkmertable databases/swissprot_sra databases/swissprot_kmertable
          echo -e "databases/swissprot_kmertable\tdatabases/swissprot_sra" > targetdbs
          echo -e "databases/res_compk" > resultlist

      - name: Build query db
        run: |
          srasearch createdb tests/MSA_Cas7-11_multiline.fa tests/querydb

      - name: Build query profile db
        run: |
          srasearch convertmsa tests/MSA_Cas7-11_multiline.fa tests/msadb
          srasearch msa2profile tests/msadb tests/query_profile

      - name: Search query against target
        run: |
          srasearch petasearch tests/querydb targetdbs resultlist alignments.m8 tmp

      - name: Search profile against target
        run: |
          srasearch petasearch tests/query_profile targetdbs resultlist alignments_profile.m8 tmp
